substitutions:
  index: "2"
  machine_index_1: "1"
  machine_index_2: "2"
  machine_index_3: "3"
  machine_index_4: "4"
  encoder_factor_1: "0.01" # NOTE: 100P/R
  encoder_factor_2: "0.01" # NOTE: 100P/R
  encoder_factor_3: "0.01" # NOTE: 100P/R
  encoder_factor_4: "0.01" # NOTE: 100P/R
  encoder_revolution_len_1: "0.174"
  encoder_revolution_len_2: "0.174"
  encoder_revolution_len_3: "0.174"
  encoder_revolution_len_4: "0.174"

packages:
  base: !include ../esphome/base.yaml
