substitutions:
  device_name: winder-${index}
  toggle_relay_below: "100"
  m_per_revolution: "0.174"

esphome:
  name: "${device_name}"

esp32:
  board: esp32dev
  framework:
    type: arduino

wifi:
  ap:
    ssid: "${device_name}"
    password: winder123

captive_portal:

improv_serial:

logger:
  level: DEBUG
  logs:
    component: ERROR
    number: INFO
    sensor: INFO

api:

ota:
  platform: esphome

i2c:
  sda: GPIO21
  scl: GPIO22
  frequency: 100kHz

pcf8574:
  - id: pcf8574_hub
    address: 0x39
    pcf8575: false

globals:
  - id: menu_editing
    type: int
    restore_value: no
    initial_value: "0"

text_sensor:
  - platform: template
    id: keypad_value
    name: Keypad value
    icon: mdi:dialpad

display:
  - platform: lcd_pcf8574
    id: lcd
    dimensions: 20x4
    address: 0x27
    lambda: |-
      id(menu).draw();

matrix_keypad:
  id: keypad
  columns:
    - pin: GPIO36
    - pin: GPIO39
    - pin: GPIO34
    - pin: GPIO35
  rows:
    # - pin: GPIO27
    - pin: GPIO26
    - pin: GPIO25
    - pin: GPIO33
    - pin: GPIO32
  # keys: "ab#*123u456d789el0rx"
  keys: "123u456d789el0rx"
  on_key:
    lambda: |-
      if (x == 117) {
        id(menu).up();
      } else if (x == 100) {
        id(menu).down();
      } else if (x == 120) {
        id(menu).enter();
      } else if (x == 101) {
        id(menu).show_main();
      } else if (x == 108) {
        id(menu).left();
      } else if (x == 114) {
        id(menu).right();
      } else {
        ESP_LOGI("keypad", "key %d pressed", x);
      }

key_collector:
  - id: collector
    source_id: keypad
    max_length: 7
    clear_keys: "e"
    allowed_keys: "0123456789"
    on_progress:
      - text_sensor.template.publish:
          id: keypad_value
          state: !lambda "return x.c_str();"

lcd_menu:
  id: menu
  display_id: lcd
  active: true
  mode: joystick
  items:
    - !include
      file: menu-item.yaml
      vars:
        machine_index: "${machine_index_1}"
    - !include
      file: menu-item.yaml
      vars:
        machine_index: "${machine_index_2}"
    - !include
      file: menu-item.yaml
      vars:
        machine_index: "${machine_index_3}"
    - !include
      file: menu-item.yaml
      vars:
        machine_index: "${machine_index_4}"

web_server:
  version: 3
  sorting_groups:
    - id: "group_machine_${machine_index_1}"
      name: "M${machine_index_1}"
      sorting_weight: 51
    - id: "group_machine_${machine_index_2}"
      name: "M${machine_index_2}"
      sorting_weight: 52
    - id: "group_machine_${machine_index_3}"
      name: "M${machine_index_3}"
      sorting_weight: 53
    - id: "group_machine_${machine_index_4}"
      name: "M${machine_index_4}"
      sorting_weight: 54

packages:
  machine_1: !include
    file: machine.yaml
    vars:
      machine_index: "${machine_index_1}"
      output_pin: 2
      run_pin: 3
      encoder_pin_a: GPIO13
      encoder_pin_b: GPIO14
      encoder_factor: "${encoder_factor_1}"
  machine_2: !include
    file: machine.yaml
    vars:
      machine_index: "${machine_index_2}"
      output_pin: 0
      run_pin: 1
      encoder_pin_a: GPIO16
      encoder_pin_b: GPIO04
      encoder_factor: "${encoder_factor_2}"
  machine_3: !include
    file: machine.yaml
    vars:
      machine_index: "${machine_index_3}"
      output_pin: 6
      run_pin: 7
      encoder_pin_a: GPIO18
      encoder_pin_b: GPIO17
      encoder_factor: "${encoder_factor_3}"
  machine_4: !include
    file: machine.yaml
    vars:
      machine_index: "${machine_index_4}"
      output_pin: 4
      run_pin: 5
      encoder_pin_a: GPIO23
      encoder_pin_b: GPIO19
      encoder_factor: "${encoder_factor_4}"
