globals:
  - id: "warmup_done_${machine_index}"
    type: bool
    restore_value: no
    initial_value: "false"

script:
  - id: "watchdog_${machine_index}"
    mode: restart
    then:
      - if:
          condition:
            lambda: "return !id(warmup_done_${machine_index});"
          then:
            - script.stop: "watchdog_${machine_index}"
      - delay: 3s
      - if:
          condition:
            binary_sensor.is_on: "run_status_${machine_index}"
          then:
            - switch.turn_on: "relay_${machine_index}"

  - id: "warmup_${machine_index}"
    mode: restart
    then:
      - delay: 40s
      - globals.set:
          id: "warmup_done_${machine_index}"
          value: "true"
      - script.execute: "watchdog_${machine_index}"

binary_sensor:
  - platform: gpio
    id: "run_status_${machine_index}"
    pin:
      pcf8574: pcf8574_hub
      number: "${run_pin}"
      mode:
        input: true
      inverted: true
    name: "Run status ${machine_index}"
    device_class: moving
    icon: mdi:run
    web_server:
      sorting_group_id: group_machine_${machine_index}
    on_press:
      - script.execute: "warmup_${machine_index}"
    on_release:
      - script.stop: "warmup_${machine_index}"
      - script.stop: "watchdog_${machine_index}"
      - globals.set:
          id: "warmup_done_${machine_index}"
          value: "false"

number:
  - platform: template
    id: "length_${machine_index}"
    name: "Length ${machine_index}"
    min_value: -9999999
    max_value: 9999999
    step: 0.001
    optimistic: true
    restore_value: yes
    initial_value: "0"
    mode: box
    device_class: distance
    unit_of_measurement: m
    icon: mdi:sync
    web_server:
      sorting_group_id: group_machine_${machine_index}
    on_value_range:
      below: "${toggle_relay_below}"
      then:
        - switch.turn_on: "relay_${machine_index}"

switch:
  - platform: gpio
    id: "relay_${machine_index}"
    name: "Relay ${machine_index}"
    pin:
      pcf8574: pcf8574_hub
      number: "${output_pin}"
      mode:
        output: true
    icon: mdi:pause
    web_server:
      sorting_group_id: group_machine_${machine_index}
    on_turn_on:
      - delay: 250ms
      - switch.turn_off: "relay_${machine_index}"

button:
  - platform: template
    name: "Reset encoder ${machine_index}"
    icon: mdi:numeric-0-circle
    web_server:
      sorting_group_id: group_machine_${machine_index}
    on_press:
      - sensor.rotary_encoder.set_value:
          id: "encoder_${machine_index}"
          value: 0
      - number.set:
          id: "length_${machine_index}"
          value: 0

sensor:
  - platform: rotary_encoder
    id: "encoder_${machine_index}"
    name: "Encoder ${machine_index}"
    pin_a:
      number: "${encoder_pin_a}"
      mode:
        input: true
        pullup: true
    pin_b:
      number: "${encoder_pin_b}"
      mode:
        input: true
        pullup: true
    icon: mdi:rotate-right
    web_server:
      sorting_group_id: group_machine_${machine_index}
    filters:
      - multiply: ${encoder_factor}
      - round: 0
      - delta: 1
    on_value:
      - script.execute: "watchdog_${machine_index}"
      - number.set:
          id: "length_${machine_index}"
          value: !lambda |-
            return id(length_${machine_index}).state - ${m_per_revolution};
